package com.example.taskfrontend.presentation.repository

import com.example.taskfrontend.presentation.model.Jenis_Makanan

class JenisMakananRepository {
    private val Jenis_Makanan = listOf(
        Jenis_Makanan(1, "https://img.freepik.com/premium-photo/nasi-goreng-malaysian-fried-rice_871710-964.jpg?w=2000", "Nasi Goreng", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 15000.00, "Fried Rice Heaven", 4.7),
        Jenis_Makanan(2, "https://www.rumahmesin.com/wp-content/uploads/2017/03/resep-sate-ayam-madura-mencicipi-makanan-asli-indonesia-yang-mendunia.jpg", "Sate Ayam", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 10000.00, "Chicken Satay Heaven", 4.8),
        Jenis_Makanan(3, "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjCUMF5qE5ZadVfVDCYHnjpPponPt8DkpoAnGGvptS5Qg9ojoTvdSRYaA-0gKGQlgI3zKbWapKUgV808Jyma5GidUsj8_FOOlQzQFyqxvjdZOEl_XnAG2WDi7th_sbI3SUc4k5KWaLsNz8IDDg58JvTOZJm6rmGypSpLcl3zu-swpQbBqaImBvHO6eF9w/s668/bakso-jumbo.png", "Bakso", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 20000.00, "Meatball Heaven", 4.5),
        Jenis_Makanan(4, "https://rinaresep.com/wp-content/uploads/2022/05/Rendang.jpg", "Rendang", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 40000.00, "Rendang Heaven", 5.0),
        Jenis_Makanan(5, "https://tse2.mm.bing.net/th?id=OIP.3Ufqd72I0mSkC7kqTeydCgHaFP&pid=Api&P=0&h=220", "Soto Ayam", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 15000.00, "Chicken Soto Heaven", 4.0),
        Jenis_Makanan(6, "http://2.bp.blogspot.com/-gS2thmF-lqk/VHM_Lam6n9I/AAAAAAAAyWY/hnzo1iJQX44/s1600/mie%2Bgoreng.jpg", "Mie Goreng", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 18000.00, "Fried Noodles Heaven", 4.4),
        Jenis_Makanan(7, "https://asset-a.grid.id/crop/0x0:0x0/700x465/photo/2019/08/29/1093597743.jpg", "Gado-Gado", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 10000.00, "Mixed vegetables with the peanut sauce Heaven", 4.3),
        Jenis_Makanan(8, "https://img.freepik.com/premium-photo/lele-goreng-fried-catfish-is-traditional-indonesian-culinary-food-catfish-chilli-tomato-paste-popular-street-food-called-pecel-lele-lamongan_511235-5139.jpg?w=2000", "Pecel lele", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 25000.00, "Catfish Pecel Heaven", 3.9),
        Jenis_Makanan(9, "https://tse2.mm.bing.net/th?id=OIP.OZioSbb72LrmbAPk0-JqvwHaE8&pid=Api&P=0&h=220", "Ayam Geprek", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 20000.00, "Smashed Chicken Heaven", 4.6),
        Jenis_Makanan(10, "https://tse2.mm.bing.net/th?id=OIP.66quj_ZHELG8Sr2wVm2izgHaE7&pid=Api&P=0&h=220", "Es Teler", "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.", 8000.00, "Ice Teler Heaven", 4.0),
    )

    fun getJenisMakanan() : List<Jenis_Makanan>{
        return Jenis_Makanan
    }

}